//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_003
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonData
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string First_Name { get; set; }
        public string Second_Name { get; set; }
        public string Number_Phone { get; set; }
        public string Pasport_Data { get; set; }

    }

    
}
